<a href="https://colab.research.google.com/github/mp308/DeepLeraning/blob/main/04_Copy_of_DeepLearning_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

iris = datasets.load_iris() #อ่านข้อมูล
X = iris.data[:, :]  #input f1, f2, f3, f4,f5
y = iris.target #output : output

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [ ]:
from keras.utils import to_categorical
y_train_onehot = to_categorical(y_train) #one hot encoding
y_test_onehot = to_categorical(y_test )
print(y_train_onehot)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
#Deep Learning
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
# create model
deep_model = Sequential()
deep_model.add(Dense(10, input_shape=(4,), kernel_initializer='normal', activation='relu'))
deep_model.add(Dense(77, kernel_initializer='normal', activation='relu'))
deep_model.add(Dense(5, kernel_initializer='normal', activation='relu'))
deep_model.add(Dense(3,  activation='softmax'))
# Compile model
deep_model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])
deep_model.fit(X_train, y_train_onehot, epochs=20) #เรียนรู้

Epoch 1/20
3/3 [==============================] - 1s 8ms/step - loss: 1.0969 - accuracy: 0.3467
Epoch 2/20
3/3 [==============================] - 0s 4ms/step - loss: 1.0930 - accuracy: 0.5467
Epoch 3/20
3/3 [==============================] - 0s 5ms/step - loss: 1.0915 - accuracy: 0.4800
Epoch 4/20
3/3 [==============================] - 0s 4ms/step - loss: 1.0891 - accuracy: 0.7333
Epoch 5/20
3/3 [==============================] - 0s 7ms/step - loss: 1.0882 - accuracy: 0.7200
Epoch 6/20
3/3 [==============================] - 0s 6ms/step - loss: 1.0851 - accuracy: 0.7333
Epoch 7/20
3/3 [==============================] - 0s 6ms/step - loss: 1.0833 - accuracy: 0.7333
Epoch 8/20
3/3 [==============================] - 0s 7ms/step - loss: 1.0764 - accuracy: 0.7067
Epoch 9/20
3/3 [==============================] - 0s 6ms/step - loss: 1.0725 - accuracy: 0.7067
Epoch 10/20
3/3 [==============================] - 0s 7ms/step - loss: 1.0674 - accuracy: 0.7333
Epoch 11/20
3/3 [======================

In [ ]:
from sklearn import metrics
import numpy as np
y_p = np.argmax(deep_model.predict(X_test),axis=1)  #เปลี่ยน onehot กลับ
print(accuracy_score(y_test, y_p)) #วัดผล metric1  :  accuracy_score
print(f1_score(y_test, y_p, average='macro')) #วัดผล metric2 :  fscore

3/3 [==============================] - 0s 3ms/step
0.6
0.5384615384615384


In [ ]:
n_neighbors = 5
knn = neighbors.KNeighborsClassifier(n_neighbors, weights="distance")
#อ่านว่า ให้ clf เรียนรู้จาก X_train, y_train
knn.fit(X_train, y_train)

KNeighborsClassifier(weights='distance')

In [ ]:
#ทดสอบ ทำนายบน X_test
y_predict = knn.predict(X_test) #ผลทำนาย
#metric : มาตรวัด
print(accuracy_score(y_test, y_predict)) #วัดผล metric1  :  accuracy_score
print(f1_score(y_test, y_predict, average='macro')) #วัดผล metric2 :  fscore

0.96
0.9623299616323684
